// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-5-QwY8CMRuXZWrNR7P5KxLydfLSeGts',
    appId: '1:407764678775:android:817a140175e00978cbee72',
    messagingSenderId: '407764678775',
    projectId: 'deliverykam-b1b3e',
    storageBucket: 'deliverykam-b1b3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqGxnoGWiixUXpMIdgynRi1vYSrM0zdxs',
    appId: '1:407764678775:ios:51f63f9641098fb8cbee72',
    messagingSenderId: '407764678775',
    projectId: 'deliverykam-b1b3e',
    storageBucket: 'deliverykam-b1b3e.appspot.com',
    iosBundleId: 'com.mizaft.kamDelivery',
  );

}